# .github/workflows/release.yml
name: Build and Release

on:
  push:
    #branches:
    #  - master
    tags:
      - 'v*'  # Only run when a tag like v1.0.0 is pushed
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.9.0  # <-- insert correct Qt version
          arch: win64_mingw  # or use `win64_msvc2019_64` if you're on MSVC

      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles" -DCMAKE_CXX_FLAGS="-static-libgcc -static-libstdc++"
          mingw32-make

      - name: Add Qt tools to PATH
        run: echo "$Env:Qt6_DIR/../../bin" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

      - name: Bundle Qt DLLs
        run: |
          windeployqt --release build\sleeptimer.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/sleeptimer.exe
            build/Qt6Core.dll
            build/Qt6Gui.dll
            build/Qt6Widgets.dll
            build/plugins/platforms/qwindows.dll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}