# .github/workflows/release.yml
name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Only run when a tag like v1.0.0 is pushed
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.9.0  # <-- insert correct Qt version
          arch: win64_mingw  # or use `win64_msvc2019_64` if you're on MSVC

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.5.3  # Or whatever you're using
          arch: win64_mingw

      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles"
          mingw32-make

      - name: Bundle Qt DLLs
        run: |
          windeployqt --release build\sleeptimer.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/sleeptimer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}